### ISSUE TITLE
Scalar cannot be indexed

### ISSUE THREAD

**Issue by achvaicer** [jfhbrook/octave-rpc#3]
Hi,

I just cloned your repo and I'm receiving this error when I try to curl.

     curl -X POST -d '{"version": "1.1", "id": "1", "method": "oneup", "params": [1]}' 10.3.1.150:8080
     {"version":"1.1","result":null,"error":["error: scalar cannot be indexed with {\n","{\"version\": \"1.1\", \"id\": \"1\", \"method\": \"oneup\", \"params\": [1]}"]}

Apparently, params are not been parsed correctly.
Do you have any idea how to fix it?

Thanks

**Comment by jfhbrook** [comment]
No idea, I forgot this project exists.
